"refactor E2E tests"

diff --git a/bin/e2e-tests b/bin/e2e-tests
--- a/bin/e2e-tests
+++ b/bin/e2e-tests
@@ -2,8 +2,8 @@
 
 set -e
 
-RED='\033[0;31m'
-GREEN='\033[0;32m'
+# RED='\033[0;31m'
+# GREEN='\033[0;32m'
 
 source "${BASH_SOURCE%/*}/.helpers.sh"
 
@@ -22,15 +22,16 @@ BIN_DIR="$(
   cd -- "$(dirname "$0")" >/dev/null 2>&1 || exit
   pwd -P
 )"
-cd "$BIN_DIR"/../e2e/scripts || exit
-/bin/sh initial-build-e2e.sh backend_myapp_"$1"
+# cd "$BIN_DIR"/../e2e/scripts || exit
+# /bin/sh initial-build-e2e.sh backend_myapp_"$1"
 
-# sleep 15 shouldnt be needed with page object navigation timeouts
+cd "$BIN_DIR"/../e2e || exit
+npm run test-local:headless
 
-if docker exec puppeteer_myapp_"$1" /bin/sh -c 'npm run test ; exit $?'; then
-  echo -e "${GREEN}\nE2E tests passed\n"
-  exit 0
-else
-  echo -e "${RED}\nE2E tests failed\n"
-  exit 1
-fi
+# if docker exec puppeteer_myapp_"$1" /bin/sh -c 'npm run test ; exit $?'; then
+#   echo -e "${GREEN}\nE2E tests passed\n"
+#   exit 0
+# else
+#   echo -e "${RED}\nE2E tests failed\n"
+#   exit 1
+# fi
