Dev (#6)
* "minimal updates"

* "bump eui"

* "remove unused env vars"

* "convenience script to dump and restore from containers"

* "refactor e2e and initial data scripts, parallelize unit-integration-tests"

* "add slice utils"

* "refactoring frontend"

* "template for admin pages - required E2E test refactor"

* "update e2e tests"

* "add notifications dummy in header"

* "working on notifications backend"

* "role column fix"

* "working on user notifications"

* "working on user notifications"

* "rename to global notifications and revert UserBase"

* "working on notifications"

* "basic backend notifications"

* "refactor notification tests"

* "working on notifications"

* "add role-based notifications and arbitrary notification fetching route"

* "test paginated fetching of notifications"

* "fix e2e tests after error handling refactor"

* "working on redux refactor back to ducks"

* "working on redux refactor of action creators"

* "update action creators"

* "logger middleware for redux"

* "update initial data scripts and e2e + async action creators"

* "working on notifications"

* "update notifications"

* "update notifications"

* "animations for notifications"

* "update before more redux refactoring"

* "initial state update"

diff --git a/bin/unit-integration-tests b/bin/unit-integration-tests
--- a/bin/unit-integration-tests
+++ b/bin/unit-integration-tests
@@ -1,9 +1,19 @@
 #!/bin/bash
 
+#
+# Run backend unit tests and frontend unit/integration tests in parallel
+#
+
+GREEN='\033[0;32m'
+RED='\033[0;32m'
+
 set -e
 
 source "${BASH_SOURCE%/*}/.helpers.sh"
 
-backend/scripts/run-tests.sh -n 4 --dist loadscope || exit 1
+backend/scripts/run-tests.sh -n auto --dist loadscope >/dev/null 2>&1 || echo -e "${RED}Backend unit tests failed${NC}" &
+cd frontend || exit && yarn test:nowatch >/dev/null 2>&1 || echo -e "${RED}Frontend unit/integration tests failed${NC}" &
 
-cd frontend || exit && yarn test:nowatch || exit 1
+echo "Waiting for tests to finish..."
+wait
+echo "All tests finished!"
